name: hive

ghc-options: -Wall

default-extensions:
  - GADTSyntax

dependencies:
  - base

library:
  source-dirs: src

executables:
  hive-server:
    main: Server.hs
    dependencies:
      - text
      - websockets

  dummy-client:
    main: Client.hs
    dependencies:
      - text
      - websockets
